name: deploy-container-app

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: 'ubuntu-latest'  
    # needs: build
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

# ------------------------------------------------------------

# REPO
    - name: ðŸ”„ downcase REPO
      uses: ASzc/change-string-case-action@v1
      id: downcase
      with:
          string: ${{ github.repository }}

    - name: â™»ï¸ Set correct environment
      run: |
        REPO=${{ steps.downcase.outputs.lowercase }}
        echo "REPO=$REPO" >> "$GITHUB_ENV"

# --------------------------------------------------------------

    - name: Deploy Container App
      uses: azure/container-apps-deploy-action@v2
      with:
        registryUrl: ghcr.io
        registryUsername: ${{ github.actor }}
        registryPassword: ${{ secrets.GITHUB_TOKEN }}
        containerAppName: try
        resourceGroup: NetworkWatcherRG
        imageToDeploy: ghcr.io/${{ env.REPO }}/my-fullstack-project



# registryId=$(az acr show --name <registry-name> --query id --output tsv)
# az role assignment create --assignee <ClientId> --scope $registryId --role AcrPush
# az role assignment create --assignee <ClientId> --scope $registryId --role AcrPull