name: deploy-container-app

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: 'ubuntu-latest'  
    # needs: build
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

# ------------------------------------------------------------
# REPO
    - name: ðŸ”„ downcase REPO
      uses: ASzc/change-string-case-action@v1
      id: downcase
      with:
          string: ${{ github.repository }}

    - name: â™»ï¸ Set correct environment
      run: |
        REPO=${{ steps.downcase.outputs.lowercase }}
        echo "REPO=$REPO" >> "$GITHUB_ENV"

# --------------------------------------------------------------

    # - name: 'Deploy Container App'
    #   uses: Azure/cli@v1
    #   with:
    #     inlineScript: |
          
    #       echo "Installing containerapp extension"
    #       az extension add --source https://workerappscliextension.blob.core.windows.net/azure-cli-extension/containerapp-0.2.0-py2.py3-none-any.whl --yes
    #       echo "Starting Deploying"
    #       az containerapp update -n try -g NetworkWatcherRG -i ghcr.io/${{ env.REPO }}/my-fullstack-project:${{ github.sha }} --registry-login-server ghcr.io --registry-username ${{ secrets.CLIENT_ID }} --registry-password ${{ secrets.CLIENT_SECRET }} --debug

    # - name: echo
    #   run:  echo "aaaaaaaaaaaaaaaaaaaaaaa   ${{ env.REPO }}"

    - name: Deploy Container App
      uses: azure/container-apps-deploy-action@v2
      with:
        registryUrl: ghcr.io
        registryUsername: ${{ github.actor }}
        registryPassword: ${{ secrets.GITHUB_TOKEN }}
        containerAppName: try
        resourceGroup: NetworkWatcherRG
        imageToDeploy: ghcr.io/${{ env.REPO }}/my-fullstack-project:${{ github.sha }}



# registryId=$(az acr show --name <registry-name> --query id --output tsv)
# az role assignment create --assignee <ClientId> --scope $registryId --role AcrPush
# az role assignment create --assignee <ClientId> --scope $registryId --role AcrPull